cd app-bar           && npm run build-and-publish && cd ..
cd bottom-nav-bar    && npm run build-and-publish && cd ..
cd button            && npm run build-and-publish && cd ..
cd card              && npm run build-and-publish && cd ..
cd checkbox          && npm run build-and-publish && cd ..
cd chip              && npm run build-and-publish && cd ..
cd core              && npm run build-and-publish && cd ..
cd dialog            && npm run build-and-publish && cd ..
cd expansion-panel   && npm run build-and-publish && cd ..
cd grid-list         && npm run build-and-publish && cd ..
cd icon              && npm run build-and-publish && cd ..
cd list              && npm run build-and-publish && cd ..
cd menu              && npm run build-and-publish && cd ..
cd nav-drawer        && npm run build-and-publish && cd ..
cd nav-item          && npm run build-and-publish && cd ..
cd radio-button      && npm run build-and-publish && cd ..
cd refresh-indicator && npm run build-and-publish && cd ..
cd search            && npm run build-and-publish && cd ..
cd switch            && npm run build-and-publish && cd ..
cd tabs              && npm run build-and-publish && cd ..
cd text-field        && npm run build-and-publish && cd ..
cd tooltip           && npm run build-and-publish && cd ..
cd router            && npm run build-and-publish && cd ..
