jsdoc2md src/app-bar/main.js > doc/an-app-bar.md
jsdoc2md src/bottom-nav-bar/main.js > doc/a-bottom-nav-bar.md
jsdoc2md src/button/main.js > doc/a-button.md
jsdoc2md src/card/main.js > doc/a-card.md
jsdoc2md src/checkbox/main.js > doc/a-checkbox.md
jsdoc2md src/chip/main.js > doc/a-chip.md
jsdoc2md src/dialog/main.js > doc/a-dialog.md
jsdoc2md src/expansion-panel/main.js > doc/an-expansion-panel.md
jsdoc2md src/grid-list/main.js > doc/a-grid-list.md
jsdoc2md src/icon/main.js > doc/an-icon.md
jsdoc2md src/list/main.js > doc/a-list.md
jsdoc2md src/menu/main.js > doc/a-manu.md
jsdoc2md src/nav-drawer/main.js > doc/a-nav-drawer.md
jsdoc2md src/radio-button/main.js > doc/a-radio-button.md
jsdoc2md src/refresh-indicator/main.js > doc/a-refresh-indicator.md
jsdoc2md src/search/main.js > doc/a-search.md
jsdoc2md src/switch/main.js > doc/a-switch.md
jsdoc2md src/tabs/main.js > doc/a-tabs.md
jsdoc2md src/text-field/main.js > doc/a-text-field.md
jsdoc2md src/tooltip/main.js > doc/a-tooltip.md

jsdoc2md src/leaflet/src/leaflet.js > doc/a-leaflet.md
jsdoc2md src/leaflet/src/marker.js > doc/a-marker.md
jsdoc2md src/router/src/router.js > doc/a-router.md
jsdoc2md src/router/src/route.js > doc/a-route.md
