jsdoc2md src/app-bar/main.js --partial docs/templates/*.hbs > docs/mce-app-bar.md
jsdoc2md src/bottom-nav-bar/main.js --partial docs/templates/*.hbs  > docs/mce-bottom-nav-bar.md
jsdoc2md src/button/main.js --partial docs/templates/*.hbs  > docs/mce-button.md
jsdoc2md src/card/main.js --partial docs/templates/*.hbs  > docs/mce-card.md
jsdoc2md src/checkbox/main.js --partial docs/templates/*.hbs > docs/mce-checkbox.md
jsdoc2md src/chip/main.js --partial docs/templates/*.hbs > docs/mce-chip.md
jsdoc2md src/dialog/main.js --partial docs/templates/*.hbs > docs/mce-dialog.md
jsdoc2md src/expansion-panel/main.js --partial docs/templates/*.hbs  > docs/mce-expansion-panel.md
jsdoc2md src/grid-list/main.js --partial docs/templates/*.hbs  > docs/mce-grid-list.md
jsdoc2md src/icon/main.js --partial docs/templates/*.hbs  > docs/mce-icon.md
jsdoc2md src/list/main.js  --partial docs/templates/*.hbs > docs/mce-list.md
jsdoc2md src/menu/main.js --partial docs/templates/*.hbs  > docs/mce-menu.md
jsdoc2md src/nav-drawer/main.js --partial docs/templates/*.hbs  > docs/mce-nav-drawer.md
jsdoc2md src/radio-button/main.js --partial docs/templates/*.hbs  > docs/mce-radio-button.md
jsdoc2md src/refresh-indicator/main.js --partial docs/templates/*.hbs  > docs/mce-refresh-indicator.md
jsdoc2md src/search/main.js --partial docs/templates/*.hbs  > docs/mce-search.md
jsdoc2md src/switch/main.js --partial docs/templates/*.hbs  > docs/mce-switch.md
jsdoc2md src/tabs/main.js --partial docs/templates/*.hbs  > docs/mce-tabs.md
jsdoc2md src/text-field/main.js --partial docs/templates/*.hbs  > docs/mce-text-field.md
jsdoc2md src/tooltip/main.js --partial docs/templates/*.hbs  > docs/mce-tooltip.md
jsdoc2md src/blocker/main.js --partial docs/templates/*.hbs  > docs/mce-blocker.md

jsdoc2md src/leaflet/src/leaflet.js --partial docs/templates/*.hbs  > docs/mce-leaflet.md
jsdoc2md src/leaflet/src/marker.js --partial docs/templates/*.hbs  > docs/mce-marker.md
jsdoc2md src/router/src/router.js --partial docs/templates/*.hbs  > docs/mce-router.md
jsdoc2md src/router/src/route.js --partial docs/templates/*.hbs  > docs/mce-route.md
