jsdoc2md src/app-bar/app-bar.js --partial docs/templates/*.hbs > docs/mce-app-bar.md
jsdoc2md src/blocker/blocker.js --partial docs/templates/*.hbs  > docs/mce-blocker.md
jsdoc2md src/bottom-nav-bar/bottom-nav-bar.js --partial docs/templates/*.hbs  > docs/mce-bottom-nav-bar.md
jsdoc2md src/button/button.js --partial docs/templates/*.hbs  > docs/mce-button.md
jsdoc2md src/card/card.js --partial docs/templates/*.hbs  > docs/mce-card.md
jsdoc2md src/checkbox/checkbox.js --partial docs/templates/*.hbs > docs/mce-checkbox.md
jsdoc2md src/chip/chip.js --partial docs/templates/*.hbs > docs/mce-chip.md
jsdoc2md src/dialog/dialog.js --partial docs/templates/*.hbs > docs/mce-dialog.md
jsdoc2md src/expansion-panel/expansion-panel.js --partial docs/templates/*.hbs  > docs/mce-expansion-panel.md
jsdoc2md src/grid-list/grid-list.js --partial docs/templates/*.hbs  > docs/mce-grid-list.md
jsdoc2md src/icon/icon.js --partial docs/templates/*.hbs  > docs/mce-icon.md
jsdoc2md src/list/list.js  --partial docs/templates/*.hbs > docs/mce-list.md
jsdoc2md src/menu/menu.js --partial docs/templates/*.hbs  > docs/mce-menu.md
jsdoc2md src/nav-drawer/nav-drawer.js --partial docs/templates/*.hbs  > docs/mce-nav-drawer.md
jsdoc2md src/radio-button/radio-button.js --partial docs/templates/*.hbs  > docs/mce-radio-button.md
jsdoc2md src/refresh-indicator/refresh-indicator.js --partial docs/templates/*.hbs  > docs/mce-refresh-indicator.md
jsdoc2md src/search/search.js --partial docs/templates/*.hbs  > docs/mce-search.md
jsdoc2md src/switch/switch.js --partial docs/templates/*.hbs  > docs/mce-switch.md
jsdoc2md src/tabs/tabs.js --partial docs/templates/*.hbs  > docs/mce-tabs.md
jsdoc2md src/text-field/text-field.js --partial docs/templates/*.hbs  > docs/mce-text-field.md
jsdoc2md src/tooltip/tooltip.js --partial docs/templates/*.hbs  > docs/mce-tooltip.md
jsdoc2md src/blocker/blocker.js --partial docs/templates/*.hbs  > docs/mce-blocker.md
jsdoc2md src/snackbar/snackbar.js --partial docs/templates/*.hbs  > docs/mce-snackbar.md

jsdoc2md src/leaflet/leaflet.js --partial docs/templates/*.hbs  > docs/mce-leaflet.md
jsdoc2md src/leaflet/marker.js --partial docs/templates/*.hbs  > docs/mce-marker.md
jsdoc2md src/router/router.js --partial docs/templates/*.hbs  > docs/mce-router.md
jsdoc2md src/router/route.js --partial docs/templates/*.hbs  > docs/mce-route.md
